# Generated by Django 3.2.6 on 2025-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mefollow',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата подписки'),
        ),
    ]
