# Generated by Django 3.2.6 on 2025-05-31 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_mefollow_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов, не менее одного')),
            ],
            options={
                'verbose_name': 'Ингредиент для рецепта',
                'verbose_name_plural': 'Ингредиенты для рецепта',
            },
        ),
        migrations.CreateModel(
            name='MeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=70, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Слаг категории')),
                ('color', models.CharField(max_length=7, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название ингредиента')),
                ('unit_of_measure', models.CharField(max_length=70, verbose_name='Единица объема')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='MeRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.CharField(max_length=150, verbose_name='Название рецепта')),
                ('discriptions', models.TextField(verbose_name='Описание рецепта')),
                ('illustration', models.ImageField(upload_to='', verbose_name='Фото рецепта')),
                ('data', models.DateTimeField(verbose_name='Дата добавления рецепта')),
                ('time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления рецепта(значение не меньше 1 минуты)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meuser', verbose_name='Автор рецепта')),
                ('category', models.ManyToManyField(related_name='me_recipes', to='recipe.MeCategory', verbose_name='Категория рецепта')),
                ('name_ingredients', models.ManyToManyField(through='recipe.IngredientsRecipe', to='recipe.MeIngredient', verbose_name='Ингредиенты для рецепта')),
                ('tags', models.ManyToManyField(related_name='me_recipes_with_tags', to='recipe.MeCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Дата добавления в список')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_cart', to='recipe.merecipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
            },
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Дата добавления рецепта в Избранное')),
                ('name_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.merecipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': ('Избранное',),
            },
        ),
        migrations.AddField(
            model_name='ingredientsrecipe',
            name='name_ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='recipe.meingredient', verbose_name='Ингридиент'),
        ),
        migrations.AddField(
            model_name='ingredientsrecipe',
            name='name_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipe.merecipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shopping_cart'),
        ),
    ]
